config/routes.rb
Rails.application.routes.draw do
  require 'sidekiq/web'

  authenticate :user, lambda { |u| u.admin? } do
    mount Sidekiq::Web => '/sidekiq'
  end

  devise_for :users, :controllers => { :omniauth_callbacks => 'omniauth_callbacks' }

  resources :users,      :only => [:index] do
    get :search, :on => :collection
  end
  resource  :avatar,     :only => [:edit, :update]
  resources :identities, :only => [:index, :destroy]

  root :to => 'welcome#index'
end

app/models/avatar.rb
class Avatar < ActiveRecord::Base
  attr_accessor :gravatar

  belongs_to :user
  belongs_to :identity

  normalize_attribute :identity_id, :with => [:strip, :blank] do |value|
    v = value.presence.try(:to_i)
    v.zero? ? nil : v
  end

  validates_inclusion_of :identity_id, :in => ->(avatar) { avatar.user.identity_ids }, :allow_nil => true

  def url
    identity ? identity.image : user.gravatar_url
  end
end

app/models/identity.rb
class Identity < ActiveRecord::Base
  belongs_to :user

  validates_presence_of   :uid, :provider
  validates_uniqueness_of :uid, :scope => :provider

  def self.find_for_oauth(auth)
    find_or_create_by(:uid => auth['uid'], :provider => auth['provider'] ) if auth
  end
end

app/models/user.rb
class User < ActiveRecord::Base
  include Gravtastic

  devise :database_authenticatable, :registerable,
         :recoverable,              :trackable,
         :validatable,              :confirmable,
         :omniauthable,             :timeoutable,
         :async

  validates_email_format_of :email,            :message    => I18n.t('email_wrong_format'),
                            :check_mx => true, :mx_message => I18n.t('no_email_servirce')

  normalize_attributes  :surname, :name, :patronymic
  validates_presence_of :surname, :name, :email

  delegate :url, :to => :avatar, :prefix => true

  VALIDATORS = {
    :should_contains_only_cyrillic_chars => /\A[а-яё -]+\z/i,
    :should_starts_with_capital_letter => /\A[А-ЯЁ]/,
    :should_looks_like_name => /\A([А-ЯЁ][а-яё]*)([ -][А-ЯЁ]?[а-яё]+)*\z/
  }

  VALIDATORS.each do |message, format|
    validates_format_of :surname, :name, :with => format, :message => message, :allow_nil => true
  end

  has_many :identities, :dependent => :destroy
  has_one  :avatar, :dependent => :destroy
  has_gravatar :secure => true, :size => 150

  after_create :create_avatar

  serialize :user_agent

  paginates_per 15

  searchable do
    string :fullname
  end

  def info
    "#{self.fullname}, #{self.email}"
  end

  def search_json
    self.as_json(:only => :id).merge(:label => info, :value => info)
  end

  def self.find_for_oauth(auth, signed_in_resource = nil)
    identity = Identity.find_for_oauth(auth)

    user = signed_in_resource ? signed_in_resource : identity.user

    user = User.new if user.nil?

    if identity.user != user
      identity.name = auth.info.name
      identity.image = auth.info.image
      identity.url = auth.info.urls.values_at('GitHub', 'Twitter', 'Facebook', 'Google', 'Vkontakte').compact[0] if auth.info.try(:urls)
      identity.user = user
      identity.save!
    end

    user
  end

  def self.new_with_session(params, session)
    super.tap do |user|
      user.identities << (Identity.find_for_oauth(session['devise.oauth_data']) || [])
    end
  end

  def self.text_search(query)
    if query.present?
      all.where('email ILIKE :query OR surname ILIKE :query OR name ILIKE :query OR patronymic ILIKE :query', :query => "%#{query}%" )
    else
      all
    end
  end

  def after_database_authentication
   RedisUserConnector.set(self.id, self.as_json(:only => [:surname, :name, :patronymic, :email], :methods => [:avatar_url]).to_a.flatten)
   RedisUserConnector.pub('broadcast', self.id)
  end

  def admin?
    role == 'admin'
  end

  def fullname
    [surname, name, patronymic].compact.join(' ')
  end

  def to_s
    "#{fullname} <#{email}>"
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception

  before_action :configure_permitted_parameters, :if => :devise_controller?
  before_action :collect_user_info
  before_action :collect_redirect_url

  private

  def configure_permitted_parameters
    devise_parameter_sanitizer.for(:sign_up) << [:surname, :name, :patronymic]
    devise_parameter_sanitizer.for(:account_update) << [:surname, :name, :patronymic]
  end

  def collect_user_info
    current_user.update_columns(:last_active_at => Time.zone.now, :user_agent => browser) if current_user
  end

  def collect_redirect_url
    session['redirect_url'] ||= params['redirect_url']
  end

  def after_sign_in_path_for(resource)
    session.delete('redirect_url') || super
  end

  def after_sign_out_path_for(resource)
    params['redirect_url'] || super
  end
end

app/controllers/avatars_controller.rb
class AvatarsController < ApplicationController
  before_action :find_avatar

  def edit
  end

  def update
    if @avatar.update(avatar_params)
      redirect_to :edit_avatar, :notice => 'Аватар успешно выбран'
    else
      flash.now[:alert] = 'При выборе аватара произошла ошибка'
      render :edit
    end
  end

  private

  def find_avatar
    @avatar = current_user.avatar
  end

  def avatar_params
    params.require(:avatar).permit(:identity_id)
  end
end

app/controllers/identities_controller.rb
class IdentitiesController < ApplicationController
  def index
    @identities = current_user.identities
  end

  def destroy
    @identity = current_user.identities.find(params[:id])
    @identity.destroy
    render :nothing => true
  end
end

app/controllers/omniauth_callbacks_controller.rb
class OmniauthCallbacksController < Devise::OmniauthCallbacksController#
  def self.provides_callback_for(provider)
    class_eval %Q{
      def #{provider}
        @user = User.find_for_oauth(env["omniauth.auth"], current_user)

        if @user.persisted?
          sign_in_and_redirect @user, event: :authentication
          @user.after_database_authentication
          set_flash_message(:notice, :success, kind: "#{provider}".capitalize) if is_navigational_format?
        else
          session["devise.oauth_data"] = env["omniauth.auth"]
          redirect_to new_user_registration_url
        end
      end
    }
  end

  Settings['providers'].each do |provider, _|
    provides_callback_for provider
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def index
    redirect_to root_path, :alert => I18n.t('not_authorized') unless current_user.present? && current_user.admin?
    @users = User.order('surname, name, patronymic').text_search(params[:search]).page params[:page]
  end

  def search
    search = User.search do
      with(:fullname).starting_with(params[:term])
    end

    render :json => search.results.map(&:search_json)
  end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  layout 'session'

  def index
    redirect_to new_user_session_path unless user_signed_in?
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/application/_footer.html.erb
<div class='footer'>
  <div class='contacts'>
    <div class='container'>
      <ul>
        <li><strong>Томский государственный университет систем управления и радиоэлектроники</strong></li>
        <li><span class='glyphicon glyphicon-map-marker'></span> 634050, г. Томск, пр. Ленина, 40</li>
      </ul>
    </div>
  </div>

  <div class='copyright'>
    <div class='container'>
      Разработка и дизайн <a href='http://tusur.ru/ru/informatization/subdivision/cvtir/'>OpenTeam</a>
    </div>
  </div>
</div>

app/views/application/_navigation.html.erb
<% content_for :tusur_header_second_menu do %>
  <ul class='nav navbar-nav hidden-sm'>
    <li class='dropdown'>
      <a href='/' class='dropdown-toggle has_arrow' data-toggle='dropdown'><%= I18n.t('app_name') %><b class='caret'></b></a>
      <%= render_navigation :renderer => :first_renderer, :level => 1 %>
    </li>
  </ul>
<% end %>

<% content_for :tusur_header_auth_block do %>
  <ul class='nav navbar-nav navbar-right auth_block'>
    <% if user_signed_in? %>
      <li class="dropdown">
        <div class="dropdown-toggle login" data-toggle='dropdown'>
          <span class='current_user truncated'>
            <%= image_tag current_user.avatar_url, :size => '24' %><%= current_user %>
            <b class='caret'></b>
          </span>
        </div>

        <ul class="dropdown-menu">
          <li>
            <%= link_to 'Выход', destroy_user_session_path, :method => :delete, :data => { :confirm => 'Вы точно, хотите выйти?' } %>
          </li>
        </ul>
      </li>
    <% else %>
      <li class='sign_in'>
        <%= link_to 'Вход в систему', new_user_session_path %>
      </li>
    <% end %>
  </ul>
<% end %>

<% content_for :tusur_header_second_menu_left do %>
  <%= render_navigation :renderer => :second_renderer %>
<% end %>

<% content_for :tusur_header_mobile_menu_block do %>
  <ul class='nav navbar-nav'>
    <%= render_navigation :renderer => :mobile_menu_renderer, :level => 1 %>
  </ul>
<% end %>

<%= render :partial => 'tusur_header/tusur_header' %>

app/views/avatars/edit.html.erb
<%= render :partial => 'commons/subnavigation' %>

<div class="tab-content">
  <%= simple_form_for @avatar, :html => { :class => 'form-avatar js-avatar' } do |f| %>
    <div class="errors">
      <%= @avatar.errors.messages.values.join %>
    </div>

    <div class="radio">
      <%= radio_button_tag 'avatar[identity_id]', 0, @avatar.identity.nil? %>
      <%= label_tag 'avatar_identity_id_0' do %>
        <%= image_tag current_user.gravatar_url, :width => 96, :height => 96 %>
        <span class="avatar-name"><%= link_to 'Gravatar', 'https://ru.gravatar.com/emails', :target => :_blank %></span>
      <% end %>
    </div>

    <% current_user.identities.each_with_index do |identity, index| %>
      <div class="radio">
        <%= radio_button_tag 'avatar[identity_id]', identity.id, @avatar.identity == identity, :id => "avatar_identity_id_#{index+1}" %>
        <%= label_tag "avatar_identity_id_#{index+1}" do %>
          <%= image_tag identity.image, :width => 96, :height => 96 %>
          <span class="avatar-name"><%= link_to identity.provider.capitalize, identity.url, :target => :_blank %></span>
        <% end %>
      </div>
    <% end %>

    <div class="actions">
      <%= f.submit 'Сохранить', :class => 'btn btn-primary' %>
    </div>
  <% end %>
</div>

app/views/commons/_subnavigation.html.erb
<div class="tab-sidebar">
  <ul class="nav">
    <% { 'Редактировать профиль' => edit_user_registration_path,  'Ключница' => identities_path, 'Аватар' => edit_avatar_path }.each do |(title, path)| %>
      <%= content_tag :li, :class => (current_page?(path) ? 'active' : 'stub') do %>
        <%= link_to title, path %>
      <% end %>
    <% end %>
  </ul>
</div>

app/views/identities/_identity.html.erb
<%= link_to identity.url, :class => 'identity' do %>
  <%= image_tag(identity.image, :width => 32, :height => 32, :title => identity.url, :class => 'account-avatar') %>
  <%= identity.provider %>
<% end %>

app/views/identities/index.html.erb
<%= render :partial => 'commons/subnavigation' %>

<div class="tab-content">
  <div class="alert alert-info">
    Чтобы закрыть доступ к учетной записи ТУСУР, удалите авторизированное приложение в настройках профиля в социальной сети.
  </div>

  <ul class="ajaxed list identities">
    <% @identities.each do |identity| %>
      <li class="list-item <%= cycle( "odd", "even" ) %>">
        <%= render :partial => 'identities/identity', :object => identity %>

        <span class="actions pull-right">
          <%= link_to '<i class="fa fa-trash-o"></i>'.html_safe, identity_path(identity),
            :data => { :confirm => 'Вы точно, хотите удалить этот аккаунт?' },
            :class => 'pull-right js-delete',
            :remote => true,
            :method => :delete %>
        </span>
      </li>
    <% end %>
  </ul>

  <ul>
    <% User.omniauth_providers.each do |provider| %>
      <li>
        <%= link_to "Связать #{provider.to_s.titleize}", omniauth_authorize_path(current_user, provider) %>
      </li>
    <% end %>
  </ul>

</div>

app/views/layouts/application.html.erb
<%= content_for :content do %>
  <h1>
    <%= I18n.t("page_title.#{controller_name}.#{action_name}") %>
  </h1>

  <%= yield %>
<% end %>

<%= render :file => 'layouts/base' %>

app/views/layouts/base.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title><%= I18n.t('app_name') %></title>
    <%= stylesheet_link_tag    'application', :media => 'all' %>
    <%= javascript_include_tag 'application' %>
    <%= csrf_meta_tags %>
    <%= favicon_link_tag 'favicon.ico'%>
  </head>
  <body>
    <div class="wrapper">
      <%= render 'navigation' %>

      <div class='container'>
        <% [notice, alert].compact.each do |flash| %>
          <div class='alert flash_message <%= alert ? 'alert-danger' : 'alert-success' %>'>
            <%= flash %>
          </div>
        <% end %>

        <%= yield :content %>
      </div>
    </div>

    <%= render :partial => 'footer' %>
    <%= render :partial => 'metrika' %>

    <%= yield :stop_ie if content_for?(:stop_ie) %>
  </body>
</html>

app/views/layouts/email.html.erb
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Strict//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-strict.dtd">
<html xmlns="http://www.w3.org/1999/xhtml" xmlns="http://www.w3.org/1999/xhtml">
  <head>
    <meta name="viewport" content="width=device-width" />
    <meta http-equiv="Content-Type" content="text/html; charset=UTF-8" />
    <link rel="stylesheet" type="text/css" href="email/application.css" />
  </head>
  <body>
    <div class="container">
      <table>
        <tbody>
          <tr>
            <td>

              <!-- header //-->
              <table class="header">
                <tbody>
                  <tr>
                    <td class="logo">
                      <%= image_tag(attachments['logo.png'].try(:url), :alt => 'ТУСУР') %>
                    </td>
                    <td>
                      <%= link_to I18n.t('app_name'), root_url, :target => :_blank %>
                    </td>
                  </tr>
                </tbody>
              </table>
              <!--// header -->

              <!-- content //-->
              <table class="content">
                <tbody>
                  <tr>
                    <td>
                      <%= yield %>
                    </td>
                  </tr>
                </tbody>
              </table>
              <!-- content //-->

              <!-- footer //-->
              <table class="footer">
                <tbody>
                  <tr>
                    <td>
                      Интересующие вас вопросы можно задать в <a href="http://profile.tusur.ru/">личном кабинете</a>
                    </td>
                    <td>
                      <strong><%= I18n.t('app_name') %></strong>
                    </td>
                  </tr>
              </table>
              <!-- footer //-->

            </td>
          </tr>
        </tbody>
      </table>
    </div>
  </body>
</html>

app/views/layouts/session.html.erb
<%= content_for :content do %>
  <div class="content <%= controller_name %>">

    <div class="account-wall">
      <h1 class="text-center form-title">
        <%= I18n.t("page_title.#{controller_name}.#{action_name}") %>
      </h1>

      <%= yield %>
    </div>

  </div>
<% end %>

<%= render :file => 'layouts/base' %>

app/views/users/index.html.erb
<%= form_tag users_path, :method => :get, :class => 'form-search' do %>
  <%= text_field_tag :search, params[:search], :autofocus => true, :class =>'string', :placeholder => 'Поиск пользователей' %>

  <%= submit_tag :search, :value => 'Поиск', :class => 'btn btn-primary btn-sm' %>
<% end %>

<div class="table-responsive">
  <table class="table table-hover table-bordered table-striped table-condensed">
    <thead>
      <tr>
        <th>ФИО</th>
        <th>Электронная почта</th>
        <th>oAuth</th>
        <th>Подтверждено</th>
        <th>Кол-во входов</th>
        <th>Последний вход</th>
        <th>Последняя активность</th>
        <th>IP</th>
        <th>Браузер</th>
      </tr>
    </thead>
    <tbody>
      <% @users.each do |user| %>
        <tr>
          <td>
            <%= user.fullname %>
            <%= content_tag :div, '(Администратор)' if user.admin? %>
          </td>
          <td><%= mail_to user.email %></td>
          <td><%= render user.identities %></td>
          <td><%= l(user.confirmed_at, :format => :long) if user.confirmed_at %></td>
          <td><%= user.sign_in_count %></td>
          <td><%= l(user.current_sign_in_at, :format => :long) if user.current_sign_in_at %></td>
          <td><%= l(user.last_active_at, :format => :long) if user.last_active_at %></td>
          <td><%= user.current_sign_in_ip %></td>
          <td><%= user.user_agent.try(:name) %> <%= user.user_agent.try(:full_version) %> (<%= user.user_agent.try(:platform) %>)</td>
        </tr>
      <% end %>
    </tbody>
  </table>
</div>

<%= paginate @users %>

app/views/welcome/index.html.erb
<div class="media">
  <%= image_tag current_user.avatar_url, :size => '150', :class => 'avatar pull-left media-object' %>

  <div class="media-body">
    <div class="info">
      <div>Вы вошли в систему как</div>
      <strong><%= "#{current_user.name} #{current_user.surname}" %></strong>
      <div><%= current_user.email %></div>
    </div>

    <ul class="actions">
      <li><%= link_to 'Изменить аватар', edit_avatar_path %></li>
      <li><%= link_to 'Редактировать профиль', edit_user_registration_path %></li>
      <li><%= link_to 'Ключница', identities_path %></li>
    </ul>
  </div>
</div>